### ISSUE TITLE
plugin wont load

### ISSUE THREAD

**Issue by Sir-Caljerque** [runih/colorscheme-picker.nvim#1]
the plugin in giving me an error saying that lazy cant clone into colorpickebamboor.nvim. could it be misspelled?
![image](https://github.com/runih/colorscheme-picker.nvim/assets/165857392/c456cec8-21b6-402d-a517-9f9cc6b29204)

**Comment by runih** [comment]
That is probably my mistake. I shouldn't add an example of a default_colorscheme with a color schema which is not a default neovim colorschema. I will change the README.md so it doesn't reference a color schema that is not installed or include the plugin that includes the color schema.

**Comment by runih** [comment]
I've change the README.md. If you change to that it should work now. Thanks for your input!
